# server sttings
server:
  port: 1323

# db settings
db:
  driver: postgres
  dsn: user=textanalysis-api dbname=textanalysis-api password=textanalysis-api-pw sslmode=disable
  datapath: ./data

# mecab settings
mecab:
  dicts:
    - /home/mkunten/dev/unidic/50a_kinsei-bungo/
