# server sttings
server:
  port: 1323

# db settings
db:
  driver: postgres
  dsn: user=texts-api dbname=texts-api password=texts-api-pw sslmode=disable
  datapath: ./data

# mecab settings
mecab:
  dicts:
    - /home/mkunten/dev/unidic/50a_kinsei-bungo/
